server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        # Fallback a index.html para HTML5 History API (React Router)
        try_files $uri $uri/ /index.html;
    }

    # Configuración de compresión gzip opcional para optimizar rendimiento
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}